[package]
name = "pgsql-sdk"
version = "0.1.0"
edition = "2021"

[lib]
create-type = "cdylib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.5"
pg_parse = "0.11"
postgres = "0.19.3"